// Synced from localapp/src/agent-client.js
// Source SHA-256: 326ff1c6ef723aed8ae4bcff177178e211683e2f9f8aa27d2d66abd224eebb09
// Do not edit this file directly.
// Run: node localapp2/tools/sync-localapp-files.mjs --write

import os from "node:os";
import process from "node:process";
import { randomUUID } from "node:crypto";
import WebSocket from "ws";

import { normalizeCommandForExecution } from "./command-runner.js";
import { logEvent } from "./logger.js";
import { SecureCommandService } from "./security/secure-command-service.js";

function createMessage(type, payload) {
  return JSON.stringify({
    type,
    payload,
    sentAt: new Date().toISOString()
  });
}

export class AgentClient {
  constructor(config, loggers, executionGateway) {
    this.config = config;
    this.agentLogger = loggers.agentLogger;
    this.commandLogger = loggers.commandLogger;
    this.executionGateway = executionGateway;
    this.socket = null;
    this.reconnectTimer = null;
    this.heartbeatTimer = null;
    this.commandQueue = [];
    this.processing = false;
    this.outbox = [];
    this.secureCommandService = new SecureCommandService(config);
  }

  start() {
    this.connect();
  }

  connect() {
    const url = new URL(this.config.serverWsUrl);
    url.searchParams.set("agentId", this.config.agentId);

    if (this.config.agentSharedToken) {
      url.searchParams.set("token", this.config.agentSharedToken);
    }

    logEvent(this.agentLogger, "info", "agent.connecting", {
      agentId: this.config.agentId,
      serverWsUrl: url.toString()
    });

    this.socket = new WebSocket(url);

    this.socket.on("open", () => {
      logEvent(this.agentLogger, "info", "agent.connected", {
        agentId: this.config.agentId
      });
      this.flushReconnectTimer();
      this.startHeartbeat();
      this.sendRegister();
      this.flushOutbox();
      this.processQueue();
    });

    this.socket.on("message", (raw) => {
      try {
        const message = JSON.parse(String(raw));
        this.handleMessage(message);
      } catch (error) {
        logEvent(this.agentLogger, "error", "agent.invalid_message", {
          agentId: this.config.agentId,
          error: error.message,
          raw: String(raw)
        });
      }
    });

    this.socket.on("close", () => {
      logEvent(this.agentLogger, "warn", "agent.disconnected", {
        agentId: this.config.agentId
      });
      this.stopHeartbeat();
      this.executionGateway.terminateRemoteSessions("agent_disconnected");
      this.scheduleReconnect();
    });

    this.socket.on("error", (error) => {
      logEvent(this.agentLogger, "error", "agent.websocket_error", {
        agentId: this.config.agentId,
        error: error.message
      });
    });
  }

  handleMessage(message) {
    if (message.type === "command.execute.secure") {
      this.handleSecureCommand(message);
      return;
    }

    if (message.type === "terminal.session.create.secure") {
      this.handleSecureTerminalSessionCreate(message);
      return;
    }

    if (message.type === "terminal.session.input.secure") {
      this.handleSecureTerminalSessionInput(message);
      return;
    }

    if (message.type === "terminal.session.terminate.secure") {
      this.handleSecureTerminalSessionTerminate(message);
      return;
    }

    if (message.type === "command.execute") {
      this.rejectInsecureCommand(message.payload || {});
      return;
    }
  }

  async processQueue() {
    if (this.processing || this.commandQueue.length === 0) {
      return;
    }

    this.processing = true;
    const payload = this.commandQueue.shift();
    const executedCommand = normalizeCommandForExecution(payload.command);

    try {
      logEvent(this.commandLogger, "info", "command.started", {
        requestId: payload.requestId,
        agentId: this.config.agentId,
        command: payload.command,
        secureStatus: payload.secureStatus || "verified",
        executedCommand
      });

      this.send(
        "command.started",
        {
          requestId: payload.requestId,
          agentId: this.config.agentId,
          secureStatus: payload.secureStatus || "verified",
          startedAt: new Date().toISOString()
        },
        true
      );

      const result = await this.executionGateway.executeCommand(payload.command);

      logEvent(
        this.commandLogger,
        result.status === "completed" ? "info" : "warn",
        "command.finished",
        {
          requestId: payload.requestId,
          agentId: this.config.agentId,
          command: payload.command,
          secureStatus: payload.secureStatus || "verified",
          securityError: "",
          ...result
        }
      );

      this.send(
        "command.finished",
        {
          requestId: payload.requestId,
          agentId: this.config.agentId,
          command: payload.command,
          secureStatus: payload.secureStatus || "verified",
          securityError: "",
          ...result
        },
        true
      );
    } catch (error) {
      this.send(
        "command.finished",
        {
          requestId: payload.requestId,
          agentId: this.config.agentId,
          command: payload.command,
          status: "failed",
          secureStatus: payload.secureStatus || "verified",
          securityError: error.message,
          exitCode: null,
          stdout: "",
          stderr: "",
          error: error.message,
          startedAt: new Date().toISOString(),
          completedAt: new Date().toISOString()
        },
        true
      );

      logEvent(this.commandLogger, "error", "command.execution_exception", {
        requestId: payload.requestId,
        agentId: this.config.agentId,
        command: payload.command,
        secureStatus: payload.secureStatus || "verified",
        error: error.message
      });
    } finally {
      this.processing = false;
      this.processQueue();
    }
  }

  sendRegister() {
    logEvent(this.agentLogger, "info", "agent.registering", {
      agentId: this.config.agentId,
      label: this.config.agentLabel
    });

    this.send("agent.register", {
      agentId: this.config.agentId,
      label: this.config.agentLabel,
      hostname: os.hostname(),
      platform: os.platform(),
      arch: os.arch(),
      pid: process.pid
    });
  }

  startHeartbeat() {
    this.stopHeartbeat();
    this.heartbeatTimer = setInterval(() => {
      this.send("agent.heartbeat", {
        agentId: this.config.agentId,
        lastSeenAt: new Date().toISOString()
      });
    }, this.config.heartbeatIntervalMs);
  }

  stopHeartbeat() {
    if (this.heartbeatTimer) {
      clearInterval(this.heartbeatTimer);
      this.heartbeatTimer = null;
    }
  }

  scheduleReconnect() {
    if (this.reconnectTimer) {
      return;
    }

    logEvent(this.agentLogger, "warn", "agent.reconnect_scheduled", {
      agentId: this.config.agentId,
      reconnectIntervalMs: this.config.reconnectIntervalMs
    });

    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = null;
      this.connect();
    }, this.config.reconnectIntervalMs);
  }

  flushReconnectTimer() {
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
  }

  flushOutbox() {
    if (this.outbox.length > 0) {
      logEvent(this.agentLogger, "info", "agent.flush_outbox", {
        agentId: this.config.agentId,
        count: this.outbox.length
      });
    }

    while (this.outbox.length > 0 && this.isOpen()) {
      const message = this.outbox.shift();
      this.socket.send(message);
    }
  }

  send(type, payload, persistIfOffline = false) {
    const message = createMessage(type, payload);

    if (this.isOpen()) {
      this.socket.send(message);
      return;
    }

    if (persistIfOffline) {
      this.outbox.push(message);
      logEvent(this.agentLogger, "warn", "agent.message_buffered", {
        agentId: this.config.agentId,
        type,
        outboxSize: this.outbox.length
      });
    }
  }

  isOpen() {
    return this.socket && this.socket.readyState === WebSocket.OPEN;
  }

  handleSecureCommand(message) {
    try {
      const unwrapped = this.secureCommandService.unwrapMessage(message);
      const payload = {
        ...unwrapped.payload,
        secureStatus: "verified",
        webserverSignFingerprint: unwrapped.meta.webserverSignFingerprint,
        authCodeId: unwrapped.meta.authCodeId
      };

      this.commandQueue.push(payload);
      logEvent(this.commandLogger, "info", "command.received_secure", {
        requestId: payload.requestId,
        agentId: this.config.agentId,
        command: payload.command,
        authCodeId: payload.authCodeId,
        webserverSignFingerprint: payload.webserverSignFingerprint,
        queueLength: this.commandQueue.length
      });
      this.processQueue();
    } catch (error) {
      this.rejectSecureCommand(message.payload || {}, error);
    }
  }

  handleSecureTerminalSessionCreate(message) {
    try {
      const unwrapped = this.secureCommandService.unwrapMessage(message, {
        expectedType: "terminal.session.create.secure",
        requiredFields: ["profile"]
      });

      const payload = unwrapped.payload;
      const session = this.executionGateway.createTerminalSession({
        sessionId: String(payload.sessionId || randomUUID()),
        agentId: this.config.agentId,
        requestId: payload.requestId,
        source: "remote",
        profileName: payload.profile,
        cwd: payload.cwd || payload.payload?.cwd,
        env: payload.env || payload.payload?.env || {},
        cols: payload.cols || payload.payload?.cols,
        rows: payload.rows || payload.payload?.rows,
        eventSink: ({ type, payload: eventPayload, persistIfOffline }) => {
          this.send(type, eventPayload, persistIfOffline);
        }
      });
    } catch (error) {
      this.send(
        "terminal.session.error",
        {
          requestId: String(message?.payload?.requestId || ""),
          agentId: this.config.agentId,
          sessionId: String(message?.payload?.sessionId || ""),
          error: error.message
        },
        true
      );

      logEvent(this.commandLogger, "warn", "terminal.session.create_rejected", {
        requestId: String(message?.payload?.requestId || ""),
        agentId: this.config.agentId,
        error: error.message
      });
    }
  }

  handleSecureTerminalSessionInput(message) {
    try {
      const unwrapped = this.secureCommandService.unwrapMessage(message, {
        expectedType: "terminal.session.input.secure",
        requiredFields: ["sessionId", "input"]
      });
      const payload = unwrapped.payload;
      this.executionGateway.writeTerminalSessionInput(
        String(payload.sessionId),
        String(payload.input)
      );
    } catch (error) {
      this.send(
        "terminal.session.error",
        {
          requestId: String(message?.payload?.requestId || ""),
          agentId: this.config.agentId,
          sessionId: String(message?.payload?.sessionId || ""),
          error: error.message
        },
        true
      );
    }
  }

  handleSecureTerminalSessionTerminate(message) {
    try {
      const unwrapped = this.secureCommandService.unwrapMessage(message, {
        expectedType: "terminal.session.terminate.secure",
        requiredFields: ["sessionId"]
      });
      const payload = unwrapped.payload;
      this.executionGateway.terminateTerminalSession(
        String(payload.sessionId),
        "remote_terminate"
      );
    } catch (error) {
      this.send(
        "terminal.session.error",
        {
          requestId: String(message?.payload?.requestId || ""),
          agentId: this.config.agentId,
          sessionId: String(message?.payload?.sessionId || ""),
          error: error.message
        },
        true
      );
    }
  }

  rejectInsecureCommand(payload) {
    const error = new Error("已拒绝未加密命令，当前 agent 仅接受 command.execute.secure");
    const requestId = String(payload.requestId || "");
    const now = new Date().toISOString();

    logEvent(this.commandLogger, "warn", "command.insecure_rejected", {
      requestId,
      agentId: this.config.agentId,
      error: error.message
    });

    if (!requestId) {
      return;
    }

    this.send(
      "command.finished",
      {
        requestId,
        agentId: this.config.agentId,
        command: String(payload.command || ""),
        status: "failed",
        secureStatus: "rejected",
        securityError: error.message,
        exitCode: null,
        stdout: "",
        stderr: "",
        error: error.message,
        startedAt: now,
        completedAt: now
      },
      true
    );
  }

  rejectSecureCommand(payload, error) {
    const requestId = String(payload.requestId || "");
    const now = new Date().toISOString();
    const message = error instanceof Error ? error.message : String(error);

    logEvent(this.commandLogger, "warn", "command.secure_rejected", {
      requestId,
      agentId: this.config.agentId,
      authCodeId: payload.authCodeId ?? null,
      error: message
    });

    if (!requestId) {
      return;
    }

    this.send(
      "command.finished",
      {
        requestId,
        agentId: this.config.agentId,
        command: "",
        status: "failed",
        secureStatus: "rejected",
        securityError: message,
        exitCode: null,
        stdout: "",
        stderr: "",
        error: message,
        startedAt: now,
        completedAt: now
      },
      true
    );
  }
}
